###
#
# td_prod.yml
#
# TD (Test Data) test data for the PROD environment
#
###

users:
  user_1:
    email: dimitrije.dragasevic@gmail.com
    password: dimitrije1994

  user_random:
    email: blablabla123
    password: 123456!