const { When, Then } = require('cucumber')
const TestData = require('../util/test_data')

When('I call this I create the first test case', { timeout: 20000 }, async function () {
  await this.loginPage.checkForClientStart()
  await this.loginPage.clickOnLoginB()
  await this.loginPage.enterEmail('user_1')
  await this.loginPage.enterPassword('user_1')
  await this.loginPage.clickOnSubmit()
  await this.loginPage.checkLogedInPage()
  await this.testPage.enterTestCaseCreation()
  await this.testPage.enterNewTestCase()
  await this.testPage.enterTitle('first')
  await this.testPage.enterDescription('first')
  await this.testPage.enterExpectedResult('first')
  await this.testPage.toogleAutomated()
  await this.testPage.enterStep(0, TestData.getUseCase('first').step_1)
  await this.testPage.addStepButton()
  await this.testPage.enterStep(1, TestData.getUseCase('first').step_2)
  await this.testPage.addStepButton()
  await this.testPage.enterStep(2, TestData.getUseCase('first').step_3)
  await this.testPage.addTestCaseButton()
})

When('I call this I create the second test case', { timeout: 20000 }, async function () {
  await this.loginPage.checkForClientStart()
  await this.loginPage.clickOnLoginB()
  await this.loginPage.enterEmail('user_1')
  await this.loginPage.enterPassword('user_1')
  await this.loginPage.clickOnSubmit()
  await this.loginPage.checkLogedInPage()
  await this.testPage.enterTestCaseCreation()
  await this.testPage.enterNewTestCase()
  await this.testPage.enterTitle('second')
  await this.testPage.enterDescription('second')
  await this.testPage.enterExpectedResult('second')
  await this.testPage.toogleAutomated()
  await this.testPage.enterStep(0, TestData.getUseCase('second').step_1)
  await this.testPage.addStepButton()
  await this.testPage.enterStep(1, TestData.getUseCase('second').step_2)
  await this.testPage.addStepButton()
  await this.testPage.enterStep(2, TestData.getUseCase('second').step_3)
  await this.testPage.addStepButton()
  await this.testPage.enterStep(3, TestData.getUseCase('second').step_4)
  await this.testPage.addStepButton()
  await this.testPage.enterStep(4, TestData.getUseCase('second').step_5)
  await this.testPage.addStepButton()
  await this.testPage.enterStep(5, TestData.getUseCase('second').step_6)
  await this.testPage.addTestCaseButton()
})

When('I call this I create the third test case', { timeout: 20000 }, async function () {
  await this.loginPage.checkForClientStart()
  await this.loginPage.clickOnLoginB()
  await this.loginPage.enterEmail('user_1')
  await this.loginPage.enterPassword('user_1')
  await this.loginPage.clickOnSubmit()
  await this.loginPage.checkLogedInPage()
  await this.testPage.enterTestCaseCreation()
  await this.testPage.enterNewTestCase()
  await this.testPage.enterTitle('third')
  await this.testPage.enterDescription('third')
  await this.testPage.enterExpectedResult('third')
  await this.testPage.toogleAutomated()
  await this.testPage.enterStep(0, TestData.getUseCase('third').step_1)
  await this.testPage.addStepButton()
  await this.testPage.enterStep(1, TestData.getUseCase('third').step_2)
  await this.testPage.addStepButton()
  await this.testPage.enterStep(2, TestData.getUseCase('third').step_3)
  await this.testPage.addStepButton()
  await this.testPage.enterStep(3, TestData.getUseCase('third').step_4)
  await this.testPage.addStepButton()
  await this.testPage.enterStep(4, TestData.getUseCase('third').step_5)
  await this.testPage.addStepButton()
  await this.testPage.enterStep(5, TestData.getUseCase('third').step_6)
  await this.testPage.addTestCaseButton()
})

When('I call this I create the fourth test case', { timeout: 20000 }, async function () {
  await this.loginPage.checkForClientStart()
  await this.loginPage.clickOnLoginB()
  await this.loginPage.enterEmail('user_1')
  await this.loginPage.enterPassword('user_1')
  await this.loginPage.clickOnSubmit()
  await this.loginPage.checkLogedInPage()
  await this.testPage.enterTestCaseCreation()
  await this.testPage.enterNewTestCase()
  await this.testPage.enterTitle('fourth')
  await this.testPage.enterDescription('fourth')
  await this.testPage.enterExpectedResult('fourth')
  await this.testPage.toogleAutomated()
  await this.testPage.enterStep(0, TestData.getUseCase('fourth').step_1)
  await this.testPage.addStepButton()
  await this.testPage.enterStep(1, TestData.getUseCase('fourth').step_2)
  await this.testPage.addStepButton()
  await this.testPage.enterStep(2, TestData.getUseCase('fourth').step_3)
  await this.testPage.addStepButton()
  await this.testPage.enterStep(3, TestData.getUseCase('fourth').step_4)
  await this.testPage.addStepButton()
  await this.testPage.enterStep(4, TestData.getUseCase('fourth').step_5)
  await this.testPage.addStepButton()
  await this.testPage.enterStep(5, TestData.getUseCase('fourth').step_6)
  await this.testPage.addTestCaseButton()
})

When('I call this I create the fifth test case', { timeout: 20000 }, async function () {
  await this.loginPage.checkForClientStart()
  await this.loginPage.clickOnLoginB()
  await this.loginPage.enterEmail('user_1')
  await this.loginPage.enterPassword('user_1')
  await this.loginPage.clickOnSubmit()
  await this.loginPage.checkLogedInPage()
  await this.testPage.enterTestCaseCreation()
  await this.testPage.enterNewTestCase()
  await this.testPage.enterTitle('fifth')
  await this.testPage.enterDescription('fifth')
  await this.testPage.enterExpectedResult('fifth')
  await this.testPage.toogleAutomated()
  await this.testPage.enterStep(0, TestData.getUseCase('fifth').step_1)
  await this.testPage.addStepButton()
  await this.testPage.enterStep(1, TestData.getUseCase('fifth').step_2)
  await this.testPage.addStepButton()
  await this.testPage.enterStep(2, TestData.getUseCase('fifth').step_3)
  await this.testPage.addStepButton()
  await this.testPage.enterStep(3, TestData.getUseCase('fifth').step_4)
  await this.testPage.addStepButton()
  await this.testPage.enterStep(4, TestData.getUseCase('fifth').step_5)
  await this.testPage.addStepButton()
  await this.testPage.enterStep(5, TestData.getUseCase('fifth').step_6)
  await this.testPage.addTestCaseButton()
})

When('I call this I create the sixth test case', { timeout: 20000 }, async function () {
  await this.loginPage.checkForClientStart()
  await this.loginPage.clickOnLoginB()
  await this.loginPage.enterEmail('user_1')
  await this.loginPage.enterPassword('user_1')
  await this.loginPage.clickOnSubmit()
  await this.loginPage.checkLogedInPage()
  await this.testPage.enterTestCaseCreation()
  await this.testPage.enterNewTestCase()
  await this.testPage.enterTitle('sixth')
  await this.testPage.enterDescription('sixth')
  await this.testPage.enterExpectedResult('sixth')
  await this.testPage.toogleAutomated()
  await this.testPage.enterStep(0, TestData.getUseCase('sixth').step_1)
  await this.testPage.addStepButton()
  await this.testPage.enterStep(1, TestData.getUseCase('sixth').step_2)
  await this.testPage.addStepButton()
  await this.testPage.enterStep(2, TestData.getUseCase('sixth').step_3)
  await this.testPage.addStepButton()
  await this.testPage.enterStep(3, TestData.getUseCase('sixth').step_4)
  await this.testPage.addStepButton()
  await this.testPage.enterStep(4, TestData.getUseCase('sixth').step_5)
  await this.testPage.addTestCaseButton()
})

When('I call this the every test case will be deleted',{timeout:20000}, async function(){
  await this.loginPage.checkForClientStart()
  await this.loginPage.clickOnLoginB()
  await this.loginPage.enterEmail('user_1')
  await this.loginPage.enterPassword('user_1')
  await this.loginPage.clickOnSubmit()
  await this.loginPage.checkLogedInPage()
  await this.testPage.enterTestCaseCreation()
  await this.testPage.deleteTestCases()
})
