const { When, Then } = require('cucumber')
const TestData = require('../util/test_data')

When('I want to add a new test cases I simply call my functions', { timeout: 20000 }, async function () {
  await this.loginPage.checkForClientStart()
  await this.loginPage.clickOnLoginB()
  await this.loginPage.enterEmail('user_1')
  await this.loginPage.enterPassword('user_1')
  await this.loginPage.clickOnSubmit()
  await this.loginPage.checkLogedInPage()
  await this.testPage.enterTestCaseCreation()
  await this.testPage.enterNewTestCase()
  await this.testPage.enterTitle(TestData.getUseCase('first').title)
  await this.testPage.enterDescription('first')
  await this.testPage.enterExpectedResult(TestData.getUseCase('first').expected_result)
  await this.testPage.enterStep(0, TestData.getUseCase('first').step_1)
  await this.testPage.addStepButton()
  await this.testPage.enterStep(1, TestData.getUseCase('first').step_2)
  await this.testPage.addStepButton()
  await this.testPage.enterStep(2, TestData.getUseCase('first').step_3)
})
